// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as AxWrapperJs from "./ax-wrapper.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function createAIClient(prim) {
  return AxWrapperJs.createAIClient(prim);
}

function generateText(prim0, prim1) {
  return AxWrapperJs.generateText(prim0, prim1);
}

function defaultConfig() {
  return {
          model: "gpt-4o-mini",
          temperature: 0.1,
          maxTokens: 2000
        };
}

async function generateSafely(client, prompt) {
  try {
    var result = await AxWrapperJs.generateText(client, prompt);
    if (result.success) {
      return {
              TAG: "Ok",
              _0: result.text
            };
    }
    var errorMsg = Core__Option.getOr(result.error, "Unknown AI generation error");
    return {
            TAG: "Error",
            _0: errorMsg
          };
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    var msg = exn.message;
    var message = msg !== undefined ? msg : "Unknown error";
    return {
            TAG: "Error",
            _0: "AI generation failed: " + message
          };
  }
}

export {
  createAIClient ,
  generateText ,
  defaultConfig ,
  generateSafely ,
}
/* ./ax-wrapper.js Not a pure module */
