// Generated by ReScript, PLEASE EDIT WITH CARE


var Button = {};

var Items = {};

var Item = {};

var Menu = {
  Button: Button,
  Items: Items,
  Item: Item
};

var Panel = {};

var Title = {};

var Description = {};

var Dialog = {
  Panel: Panel,
  Title: Title,
  Description: Description
};

var Switch = {};

export {
  Menu ,
  Dialog ,
  Switch ,
}
/* No side effect */
