// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Playwright from "./Playwright.res.mjs";

var Locator = {};

async function waitForSelector(_page, param, param$1, param$2) {
  setTimeout((function () {
          
        }), 100);
}

async function getHomepageContent(page, _content) {
  return await page.title();
}

async function clickNavigation(page, _nav) {
  return await page.goto("/");
}

async function isNavigationVisible(_page, _nav) {
  return true;
}

async function isLayoutVisible(_page, _layout) {
  return true;
}

var TypedPage = {
  waitForSelector: waitForSelector,
  getHomepageContent: getHomepageContent,
  clickNavigation: clickNavigation,
  isNavigationVisible: isNavigationVisible,
  isLayoutVisible: isLayoutVisible
};

var Browser = Playwright.Browser;

var Page = Playwright.Page;

var Browsers = Playwright.Browsers;

export {
  Browser ,
  Page ,
  Browsers ,
  Locator ,
  TypedPage ,
}
/* No side effect */
