// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StyleProps from "../core/StyleProps.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as DesignSystem from "../core/DesignSystem.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  var __disabled = props.disabled;
  var size = props.size;
  var __variant = props.variant;
  var variant = __variant !== undefined ? __variant : "Primary";
  var disabled = __disabled !== undefined ? __disabled : false;
  var stylePropsValue = Core__Option.getOr(props.styleProps, StyleProps.empty);
  var variantClasses = variant === "Warning" ? [
      "px-4 py-2 rounded-md font-medium",
      DesignSystem.backgroundColorToClass("Warning"),
      DesignSystem.colorToClass("Inverse"),
      "hover:opacity-90",
      "focus:ring-2 focus:ring-offset-2 focus:ring-amber-500",
      "disabled:opacity-50 disabled:cursor-not-allowed",
      "transition-all duration-200"
    ] : (
      variant === "Secondary" ? [
          "px-4 py-2 rounded-md font-medium border",
          DesignSystem.backgroundColorToClass("Secondary"),
          DesignSystem.colorToClass("Primary"),
          DesignSystem.borderColorToClass("Primary"),
          "hover:bg-blue-50",
          "focus:ring-2 focus:ring-offset-2 focus:ring-blue-500",
          "disabled:opacity-50 disabled:cursor-not-allowed",
          "transition-all duration-200"
        ] : (
          variant === "Success" ? [
              "px-4 py-2 rounded-md font-medium",
              DesignSystem.backgroundColorToClass("Success"),
              DesignSystem.colorToClass("Inverse"),
              "hover:opacity-90",
              "focus:ring-2 focus:ring-offset-2 focus:ring-green-500",
              "disabled:opacity-50 disabled:cursor-not-allowed",
              "transition-all duration-200"
            ] : (
              variant === "Error" ? [
                  "px-4 py-2 rounded-md font-medium",
                  DesignSystem.backgroundColorToClass("Error"),
                  DesignSystem.colorToClass("Inverse"),
                  "hover:opacity-90",
                  "focus:ring-2 focus:ring-offset-2 focus:ring-red-500",
                  "disabled:opacity-50 disabled:cursor-not-allowed",
                  "transition-all duration-200"
                ] : (
                  variant === "Ghost" ? [
                      "px-4 py-2 rounded-md font-medium",
                      DesignSystem.colorToClass("Primary"),
                      "hover:bg-gray-100",
                      "focus:ring-2 focus:ring-offset-2 focus:ring-blue-500",
                      "disabled:opacity-50 disabled:cursor-not-allowed",
                      "transition-all duration-200"
                    ] : [
                      "px-4 py-2 rounded-md font-medium",
                      DesignSystem.backgroundColorToClass("Primary"),
                      DesignSystem.colorToClass("Inverse"),
                      "hover:opacity-90",
                      "focus:ring-2 focus:ring-offset-2 focus:ring-blue-500",
                      "disabled:opacity-50 disabled:cursor-not-allowed",
                      "transition-all duration-200"
                    ]
                )
            )
        )
    );
  var sizeClasses = size !== undefined ? [StyleProps.sizeToClass(size)] : [];
  var styleClasses = StyleProps.toClasses(stylePropsValue);
  var allClasses = variantClasses.concat(sizeClasses).concat(styleClasses);
  var className = DesignSystem.cx(allClasses);
  return JsxRuntime.jsx("button", {
              children: props.children,
              className: className,
              disabled: disabled,
              onClick: props.onClick
            });
}

var make = Button;

export {
  make ,
}
/* DesignSystem Not a pure module */
