// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Text from "./Text.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function heading(text, levelOpt, color, styleProps) {
  var level = levelOpt !== undefined ? levelOpt : "h2";
  var tag = level === "h2" ? "h2" : (
      level === "h3" ? "h3" : (
          level === "h4" ? "h4" : "h1"
        )
    );
  var variant = level === "h2" ? "Title" : (
      level === "h3" ? "Heading" : (
          level === "h4" ? "Subheading" : "Display"
        )
    );
  return JsxRuntime.jsx($$Text.make, {
              tag: tag,
              variant: variant,
              color: color,
              styleProps: styleProps,
              children: text
            });
}

function paragraph(text, color, styleProps) {
  return JsxRuntime.jsx($$Text.make, {
              variant: "Body",
              color: color,
              styleProps: styleProps,
              children: text
            });
}

function label(text, color, styleProps) {
  return JsxRuntime.jsx($$Text.make, {
              tag: "label",
              variant: "Label",
              color: color,
              styleProps: styleProps,
              children: text
            });
}

var Create = {
  heading: heading,
  paragraph: paragraph,
  label: label
};

var $$Text$1;

var Button;

var Container;

var Section;

var StyleProps;

export {
  $$Text$1 as $$Text,
  Button ,
  Container ,
  Section ,
  StyleProps ,
  Create ,
}
/* Text Not a pure module */
