// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StyleProps from "../core/StyleProps.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as DesignSystem from "../core/DesignSystem.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Container(props) {
  var __padding = props.padding;
  var __maxWidth = props.maxWidth;
  var maxWidth = __maxWidth !== undefined ? __maxWidth : "lg";
  var padding = __padding !== undefined ? __padding : true;
  var stylePropsValue = Core__Option.getOr(props.styleProps, StyleProps.empty);
  var containerClasses = [
      "mx-auto",
      maxWidth === "lg" ? "max-w-4xl" : (
          maxWidth === "md" ? "max-w-md" : (
              maxWidth === "sm" ? "max-w-sm" : (
                  maxWidth === "xl" ? "max-w-6xl" : "max-w-full"
                )
            )
        ),
      padding ? "px-4 sm:px-6 lg:px-8" : ""
    ].filter(function (cls) {
        return cls !== "";
      });
  var styleClasses = StyleProps.toClasses(stylePropsValue);
  var allClasses = containerClasses.concat(styleClasses);
  var className = DesignSystem.cx(allClasses);
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: className
            });
}

var make = Container;

export {
  make ,
}
/* DesignSystem Not a pure module */
