// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StyleProps from "../core/StyleProps.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as DesignSystem from "../core/DesignSystem.res.mjs";
import * as ThemeContext from "../core/ThemeContext.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Section(props) {
  var __variant = props.variant;
  var variant = __variant !== undefined ? __variant : "Regular";
  var themedStyle = ThemeContext.useThemedStyle();
  var stylePropsValue = Core__Option.getOr(props.styleProps, StyleProps.empty);
  var variantClasses = variant === "Compact" ? ["py-8 sm:py-12"] : (
      variant === "Hero" ? [
          "py-16 sm:py-24 lg:py-32",
          themedStyle.getBgColorClass("Primary") + " bg-opacity-5"
        ] : ["py-12 sm:py-16"]
    );
  var styleClasses = StyleProps.toClasses(stylePropsValue);
  var allClasses = variantClasses.concat(styleClasses);
  var className = DesignSystem.cx(allClasses);
  return JsxRuntime.jsx("section", {
              children: props.children,
              className: className
            });
}

var make = Section;

export {
  make ,
}
/* DesignSystem Not a pure module */
