// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ChromaJs from "chroma-js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function generateScale(baseColor) {
  var scale = ChromaJs.scale([
          "#ffffff",
          "#f9fafb",
          "#f3f4f6",
          "#e5e7eb",
          "#d1d5db",
          baseColor,
          baseColor,
          baseColor,
          baseColor,
          "#111827",
          "#030712"
        ]).mode("lab");
  var colors = scale.colors(11);
  return {
          c50: Belt_Option.getWithDefault(colors[0], "#ffffff"),
          c100: Belt_Option.getWithDefault(colors[1], "#f9fafb"),
          c200: Belt_Option.getWithDefault(colors[2], "#f3f4f6"),
          c300: Belt_Option.getWithDefault(colors[3], "#e5e7eb"),
          c400: Belt_Option.getWithDefault(colors[4], "#d1d5db"),
          c500: Belt_Option.getWithDefault(colors[5], baseColor),
          c600: Belt_Option.getWithDefault(colors[6], baseColor),
          c700: Belt_Option.getWithDefault(colors[7], baseColor),
          c800: Belt_Option.getWithDefault(colors[8], baseColor),
          c900: Belt_Option.getWithDefault(colors[9], "#111827"),
          c950: Belt_Option.getWithDefault(colors[10], "#030712")
        };
}

function createPalette(config) {
  var primaryScale = generateScale(config.baseColor);
  var neutralScale = generateScale("#6b7280");
  var successScale = generateScale("#059669");
  var warningScale = generateScale("#d97706");
  var errorScale = generateScale("#dc2626");
  var infoScale = generateScale("#2563eb");
  return {
          primary: primaryScale,
          neutral: neutralScale,
          success: successScale,
          warning: warningScale,
          error: errorScale,
          info: infoScale
        };
}

var defaultPalette = createPalette({
      baseColor: "#3b82f6",
      name: "default"
    });

function getColorFromScale(scale, intensity) {
  switch (intensity) {
    case "C50" :
        return scale.c50;
    case "C100" :
        return scale.c100;
    case "C200" :
        return scale.c200;
    case "C300" :
        return scale.c300;
    case "C400" :
        return scale.c400;
    case "C500" :
        return scale.c500;
    case "C600" :
        return scale.c600;
    case "C700" :
        return scale.c700;
    case "C800" :
        return scale.c800;
    case "C900" :
        return scale.c900;
    case "C950" :
        return scale.c950;
    
  }
}

export {
  generateScale ,
  createPalette ,
  defaultPalette ,
  getColorFromScale ,
}
/* defaultPalette Not a pure module */
