// Generated by ReScript, PLEASE EDIT WITH CARE


var baseUrl = "https://your-site.com";

var logo = baseUrl + "/logo.svg";

var ogImage = baseUrl + "/og-image.svg";

var appleTouchIcon = baseUrl + "/apple-touch-icon.svg";

var favicon = baseUrl + "/favicon.svg";

var Urls = {
  baseUrl: baseUrl,
  github: "https://github.com/your-username/your-repo",
  logo: logo,
  ogImage: ogImage,
  appleTouchIcon: appleTouchIcon,
  favicon: favicon
};

var Api = {
  health: "/api/health"
};

var Timing = {
  apiTimeout: 30000,
  shortTimeout: 10000,
  scrollDelay: 100,
  typingDelay: 200
};

function durationToMs(duration) {
  switch (duration) {
    case "Fast" :
        return 150;
    case "Medium" :
        return 300;
    case "Slow" :
        return 500;
    
  }
}

function durationToDelay(duration) {
  switch (duration) {
    case "Fast" :
        return "0.15s";
    case "Medium" :
        return "0.3s";
    case "Slow" :
        return "0.5s";
    
  }
}

var $$Animation = {
  durationToMs: durationToMs,
  durationToDelay: durationToDelay,
  delay0: "0s",
  delay200: "0.2s",
  delay400: "0.4s"
};

var maxWidthMd = "max-w-4xl";

var Layout = {
  maxWidthSm: "max-w-2xl",
  maxWidthMd: maxWidthMd,
  maxWidthLg: "max-w-6xl",
  maxWidthXl: "max-w-7xl",
  contentWidth: maxWidthMd
};

export {
  Urls ,
  Api ,
  Timing ,
  $$Animation ,
  Layout ,
}
/* No side effect */
