// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ColorPalette from "./ColorPalette.res.mjs";

var testPalette = ColorPalette.createPalette({
      baseColor: "#ff6b35",
      name: "test"
    });

var palette = testPalette;

export {
  testPalette ,
  palette ,
}
/* testPalette Not a pure module */
