// Generated by ReScript, PLEASE EDIT WITH CARE


function tagToString(tag) {
  if (tag === "mark") {
    return "mark";
  } else if (tag === "span") {
    return "span";
  } else if (tag === "textarea") {
    return "textarea";
  } else if (tag === "button") {
    return "button";
  } else if (tag === "section") {
    return "section";
  } else if (tag === "article") {
    return "article";
  } else if (tag === "label") {
    return "label";
  } else if (tag === "footer") {
    return "footer";
  } else if (tag === "header") {
    return "header";
  } else if (tag === "small") {
    return "small";
  } else if (tag === "a") {
    return "a";
  } else if (tag === "p") {
    return "p";
  } else if (tag === "em") {
    return "em";
  } else if (tag === "h1") {
    return "h1";
  } else if (tag === "h2") {
    return "h2";
  } else if (tag === "h3") {
    return "h3";
  } else if (tag === "h4") {
    return "h4";
  } else if (tag === "h5") {
    return "h5";
  } else if (tag === "h6") {
    return "h6";
  } else if (tag === "div") {
    return "div";
  } else if (tag === "strong") {
    return "strong";
  } else if (tag === "input") {
    return "input";
  } else {
    return "main";
  }
}

function isValidForStyle(tag, style) {
  if (tag === "div" || tag === "p" || tag === "span") {
    switch (style) {
      case "Display" :
      case "Title" :
      case "Heading" :
          return false;
      default:
        return true;
    }
  } else {
    if (tag === "label") {
      if (style === "Label") {
        return true;
      } else {
        return false;
      }
    }
    if (tag === "strong" || tag === "em") {
      switch (style) {
        case "Body" :
        case "Caption" :
            return true;
        default:
          return false;
      }
    } else {
      if (!(tag === "h3" || tag === "h2" || tag === "h1")) {
        return false;
      }
      switch (style) {
        case "Display" :
        case "Title" :
        case "Heading" :
            return true;
        default:
          return false;
      }
    }
  }
}

var $$Text = {
  isValidForStyle: isValidForStyle
};

function defaultTag(href) {
  if (href !== undefined) {
    return "a";
  } else {
    return "button";
  }
}

var Button = {
  defaultTag: defaultTag
};

export {
  tagToString ,
  $$Text ,
  Button ,
}
/* No side effect */
