// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var routes = [
  {
    id: "Home",
    path: "/",
    title: "SalesEscape - Escape Salesforce costs with AI automation",
    description: "Replace expensive Salesforce with AI-first revenue operations. Cut costs by 80% while increasing efficiency."
  },
  {
    id: "CaseStudy",
    path: "/case-study",
    title: "Case Study: 80% Cost Reduction - SalesEscape",
    description: "50-person sales team replaces Salesforce with AI-first revenue operations and saves $12.3k monthly."
  },
  {
    id: "Analyze",
    path: "/analyze",
    title: "Salesforce Cost Calculator - SalesEscape",
    description: "AI analyzes your Salesforce setup and finds optimization opportunities. Get instant cost savings estimates."
  },
  {
    id: "About",
    path: "/about",
    title: "About - Ex-Salesforce Developer - SalesEscape",
    description: "Built by an ex-Salesforce developer who escaped the ecosystem and helps others do the same."
  }
];

function getRoute(pageId) {
  return Core__Option.getOr(routes.find(function (r) {
                  return r.id === pageId;
                }), {
              id: "Home",
              path: "/",
              title: "SalesEscape",
              description: "Escape Salesforce costs"
            });
}

function getPath(pageId) {
  return getRoute(pageId).path;
}

function getTitle(pageId) {
  return getRoute(pageId).title;
}

function getDescription(pageId) {
  return getRoute(pageId).description;
}

function Routes$SafeLink(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  var path = getRoute(props.to).path;
  return JsxRuntime.jsx(Link, {
              href: path,
              className: className,
              children: props.children
            });
}

var SafeLink = {
  make: Routes$SafeLink
};

export {
  routes ,
  getRoute ,
  getPath ,
  getTitle ,
  getDescription ,
  SafeLink ,
}
/* next/link Not a pure module */
