// Generated by ReScript, PLEASE EDIT WITH CARE


function fontSizeToClass(size) {
  if (size === "SM") {
    return "text-sm";
  } else if (size === "XL") {
    return "text-xl";
  } else if (size === "XS") {
    return "text-xs";
  } else if (size === "XL2") {
    return "text-2xl";
  } else if (size === "XL3") {
    return "text-3xl";
  } else if (size === "XL4") {
    return "text-4xl";
  } else if (size === "XL5") {
    return "text-5xl";
  } else if (size === "XL6") {
    return "text-6xl";
  } else if (size === "Base") {
    return "text-base";
  } else {
    return "text-lg";
  }
}

function fontWeightToClass(weight) {
  if (weight === "Normal") {
    return "font-normal";
  } else if (weight === "ExtraLight") {
    return "font-extralight";
  } else if (weight === "Light") {
    return "font-light";
  } else if (weight === "ExtraBold") {
    return "font-extrabold";
  } else if (weight === "SemiBold") {
    return "font-semibold";
  } else if (weight === "Bold") {
    return "font-bold";
  } else if (weight === "Medium") {
    return "font-medium";
  } else if (weight === "Thin") {
    return "font-thin";
  } else {
    return "font-black";
  }
}

function spacingToClass(space, property) {
  var sizeValue = space === 1 ? "1" : (
      space === 2 ? "2" : (
          space === 3 ? "3" : (
              space === 4 ? "4" : (
                  space === 5 ? "5" : (
                      space === 6 ? "6" : (
                          space === 8 ? "8" : (
                              space === 10 ? "10" : (
                                  space === 12 ? "12" : (
                                      space === 16 ? "16" : (
                                          space === 20 ? "20" : (
                                              space === 24 ? "24" : (
                                                  space === 32 ? "32" : (
                                                      space === 40 ? "40" : (
                                                          space === 48 ? "48" : (
                                                              space === 64 ? "64" : "0"
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    );
  var prefix = property === "p" ? "p-" : (
      property === "mb" ? "mb-" : (
          property === "ml" ? "ml-" : (
              property === "mr" ? "mr-" : (
                  property === "mt" ? "mt-" : (
                      property === "mx" ? "mx-" : (
                          property === "my" ? "my-" : (
                              property === "pb" ? "pb-" : (
                                  property === "pl" ? "pl-" : (
                                      property === "pr" ? "pr-" : (
                                          property === "pt" ? "pt-" : (
                                              property === "px" ? "px-" : (
                                                  property === "py" ? "py-" : "m-"
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    );
  return prefix + sizeValue;
}

function textAlignToClass(align) {
  if (align === "Right") {
    return "text-right";
  } else if (align === "Left") {
    return "text-left";
  } else if (align === "Center") {
    return "text-center";
  } else {
    return "text-justify";
  }
}

function lineHeightToClass(height) {
  if (height === "Loose") {
    return "leading-loose";
  } else if (height === "Tight") {
    return "leading-tight";
  } else if (height === "Relaxed") {
    return "leading-relaxed";
  } else {
    return "leading-normal";
  }
}

export {
  fontSizeToClass ,
  fontWeightToClass ,
  spacingToClass ,
  textAlignToClass ,
  lineHeightToClass ,
}
/* No side effect */
