// Generated by ReScript, PLEASE EDIT WITH CARE


var Layout = {
  container: "[data-testid='layout-container']",
  navigation: "[data-testid='main-navigation']"
};

var $$Navigation = {
  logo: "[data-testid='logo-link']",
  homeLink: "[data-testid='home-link']",
  analyzeLink: "[data-testid='analyze-link']",
  caseStudyLink: "[data-testid='case-study-link']"
};

var Analyze = {
  heroHeading: "[data-testid='analyze-hero-heading']",
  chatContainer: "[data-testid='salesforce-chat']",
  demoButton: "[data-testid='demo-calculator-button']"
};

var CaseStudy = {
  heroHeading: "[data-testid='case-study-hero-heading']",
  savingsCard: "[data-testid='monthly-savings-card']",
  roiCard: "[data-testid='roi-card']"
};

var Buttons = {
  bookCallDesktop: "[data-testid='book-call-desktop']",
  bookCallMobile: "[data-testid='book-call-mobile']",
  primary: "[data-testid='primary-button']",
  secondary: "[data-testid='secondary-button']"
};

export {
  Layout ,
  $$Navigation ,
  Analyze ,
  CaseStudy ,
  Buttons ,
}
/* No side effect */
