// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainLayout from "./layouts/MainLayout.res.mjs";
import * as Router from "next/router";
import * as JsxRuntime from "react/jsx-runtime";

function $$default(props) {
  Router.useRouter();
  var content = React.createElement(props.Component, props.pageProps);
  return JsxRuntime.jsx(MainLayout.make, {
              children: content
            });
}

export {
  $$default as default,
}
/* react Not a pure module */
