// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Text from "./components/Text.res.mjs";
import * as Button from "./components/Button.res.mjs";
import * as Section from "./components/Section.res.mjs";
import * as Container from "./components/Container.res.mjs";
import * as MainLayout from "./layouts/MainLayout.res.mjs";
import * as ThemeContext from "./core/ThemeContext.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Index(props) {
  return JsxRuntime.jsx(ThemeContext.ThemeProvider.make, {
              children: JsxRuntime.jsx(MainLayout.make, {
                    children: JsxRuntime.jsx(Container.make, {
                          children: JsxRuntime.jsx(Section.make, {
                                variant: "Hero",
                                children: JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx($$Text.make, {
                                              variant: "Display",
                                              color: "Primary",
                                              children: "Minimalist Design System"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: JsxRuntime.jsx($$Text.make, {
                                                    variant: "Body",
                                                    color: "Secondary",
                                                    children: "A simple palette inspired by Dieter Rams: clear hierarchy, minimal distraction."
                                                  }),
                                              className: "max-w-2xl mx-auto"
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx(Button.make, {
                                                      variant: "Primary",
                                                      children: "Primary Button"
                                                    }),
                                                JsxRuntime.jsx(Button.make, {
                                                      variant: "Secondary",
                                                      children: "Secondary Button"
                                                    }),
                                                JsxRuntime.jsx(Button.make, {
                                                      variant: "Success",
                                                      children: "Success Button"
                                                    })
                                              ],
                                              className: "flex gap-4 justify-center flex-wrap"
                                            })
                                      ],
                                      className: "text-center space-y-8"
                                    })
                              })
                        })
                  })
            });
}

var DS;

var make = Index;

export {
  DS ,
  make ,
}
/* Text Not a pure module */
