// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as DesignSystem from "../core/DesignSystem.res.mjs";
import * as ThemeContext from "../core/ThemeContext.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function MainLayout(props) {
  var themedStyle = ThemeContext.useThemedStyle();
  var layoutClasses = DesignSystem.cx(Belt_Array.concatMany([
            [
              "min-h-screen",
              themedStyle.getBgColorClass("Primary") + " bg-opacity-5",
              themedStyle.getTextColorClass("Primary")
            ],
            themedStyle.getMotionClasses()
          ]));
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("main", {
                    children: props.children
                  }),
              className: layoutClasses
            });
}

var make = MainLayout;

export {
  make ,
}
/* DesignSystem Not a pure module */
